/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2025-02-12 07:00:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class module2_005fview_005fcalculation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Calculated Results Data</title>\r\n");
      out.write("    <style>\r\n");
      out.write("      body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-image: url('clv.jpg');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0px 6px 18px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            overflow-x: auto; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: black;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 14px 18px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            word-wrap: break-word;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(111, 159, 255, 0.8), rgba(76, 175, 80, 0.8));\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th:hover {\r\n");
      out.write("            background-color: rgba(62, 142, 65, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:nth-child(even) {\r\n");
      out.write("            background-color: rgba(242, 242, 242, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:hover {\r\n");
      out.write("            background-color: rgba(224, 247, 250, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-button {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            background-color: rgba(76, 175, 80, 0.8);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-button:hover {\r\n");
      out.write("            background-color: rgba(62, 142, 65, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            table, thead, tbody, th, td, tr {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            th {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            tr {\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("                box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            td {\r\n");
      out.write("                position: relative;\r\n");
      out.write("                padding-left: 50%;\r\n");
      out.write("                text-align: right;\r\n");
      out.write("                background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("                border-bottom: 1px solid #ddd;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            td:before {\r\n");
      out.write("                content: attr(data-label);\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                width: 45%;\r\n");
      out.write("                padding-left: 15px;\r\n");
      out.write("                text-align: left;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                text-transform: uppercase;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            tr:hover {\r\n");
      out.write("                background-color: rgba(255, 255, 255, 0.8); \r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            td {\r\n");
      out.write("                font-size: 0.9em;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1 style=\"color: black; text-transform: uppercase;\">Calculated Results Data</h1>\r\n");
      out.write("    <table id=\"myTable\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th onclick=\"sortTable(0)\">S.No</th>\r\n");
      out.write("                <th onclick=\"sortTable(1)\">Employee ID</th>\r\n");
      out.write("                <th onclick=\"sortTable(2)\">Fruits/Veggies</th>\r\n");
      out.write("                <th onclick=\"sortTable(3)\">Remaining Tons Needed</th>\r\n");
      out.write("                <th onclick=\"sortTable(4)\">Estimated Time (Days)</th>\r\n");
      out.write("                <th onclick=\"sortTable(5)\">Total Quantity Available</th>\r\n");
      out.write("                <th onclick=\"sortTable(6)\">Projected Growth Next Month</th>\r\n");
      out.write("                <th onclick=\"sortTable(7)\">Inventory Turnover Rate</th>\r\n");
      out.write("                <th onclick=\"sortTable(8)\">Days Until Full Stock</th>\r\n");
      out.write("                <th onclick=\"sortTable(9)\">Supply Deficit</th>\r\n");
      out.write("                <th onclick=\"sortTable(10)\">Growth Potential</th>\r\n");
      out.write("                <th onclick=\"sortTable(11)\">Current Stock Status</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");

                String jdbcUrl = "jdbc:mysql://localhost:3306/vertical_farming"; 
                String dbUser = "root"; 
                String dbPassword = "root"; 

                Connection conn = null;
                Statement stmt = null;
                ResultSet rs = null;
                try {
                    Class.forName("com.mysql.jdbc.Driver"); 
                    conn = DriverManager.getConnection(jdbcUrl, dbUser, dbPassword);
                    stmt = conn.createStatement();
                    String sql = "SELECT * FROM module2_calculated_result"; // Updated to fetch from the new table
                    rs = stmt.executeQuery(sql);

                    int index = 1; // To keep track of serial numbers
                    while (rs.next()) {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td data-label=\"S.No\">");
      out.print( index++ );
      out.write("</td> <!-- Incremental Serial No -->\r\n");
      out.write("                            <td data-label=\"Employee ID\">");
      out.print( rs.getString("employee_id") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Fruits/Veggies\">");
      out.print( rs.getString("fruits_vegetables") != null ? rs.getString("fruits_vegetables") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Remaining Tons Needed\">");
      out.print( rs.getString("remaining_tons_needed") != null ? rs.getString("remaining_tons_needed") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Estimated Time (Days)\">");
      out.print( rs.getString("estimated_time_days") != null ? rs.getString("estimated_time_days") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Total Quantity Available\">");
      out.print( rs.getString("total_quantity_available") != null ? rs.getString("total_quantity_available") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Projected Growth Next Month\">");
      out.print( rs.getString("projected_growth_next_month") != null ? rs.getString("projected_growth_next_month") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Inventory Turnover Rate\">");
      out.print( rs.getString("inventory_turnover_rate") != null ? rs.getString("inventory_turnover_rate") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Days Until Full Stock\">");
      out.print( rs.getString("days_until_full_stock") != null ? rs.getString("days_until_full_stock") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Supply Deficit\">");
      out.print( rs.getString("supply_deficit") != null ? rs.getString("supply_deficit") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Growth Potential\">");
      out.print( rs.getString("growth_potential") != null ? rs.getString("growth_potential") : "N/A" );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Current Stock Status\">");
      out.print( rs.getString("current_stock_status") != null ? rs.getString("current_stock_status") : "N/A" );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                    }
                } catch (SQLException e) {
                    out.println("<tr><td colspan='12'>Error fetching data: " + e.getMessage() + "</td></tr>");
                } finally {
                    // Close resources
                    try {
                        if (rs != null) rs.close();
                        if (stmt != null) stmt.close();
                        if (conn != null) conn.close();
                    } catch (SQLException e) {
                        out.println("<tr><td colspan='12'>Error closing resources: " + e.getMessage() + "</td></tr>");
                    }
                }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"back-button\" onclick=\"window.location.href='module2_product_availability.html'\">Back</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Sorting function remains the same\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
