/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2025-02-12 07:13:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class module3_005fculativation_005fprocess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Vegetable Request Table</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-image: url('clv.jpg'); /* Set your background image here */\r\n");
      out.write("            background-size: cover; /* Cover the entire background */\r\n");
      out.write("            background-repeat: no-repeat; /* Prevent tiling */\r\n");
      out.write("            background-position: center; /* Center the image */\r\n");
      out.write("            color: white; /* Change text color to white for better visibility */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0px 6px 18px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            overflow-x: auto; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: black;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 14px 18px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            word-wrap: break-word;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(111, 159, 255, 0.8), rgba(76, 175, 80, 0.8));\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th:hover {\r\n");
      out.write("            background-color: rgba(62, 142, 65, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:nth-child(even) {\r\n");
      out.write("            background-color: rgba(242, 242, 242, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:hover {\r\n");
      out.write("            background-color: rgba(224, 247, 250, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Back button styling */\r\n");
      out.write("        .back-button {\r\n");
      out.write("            position: fixed; /* Fixed position */\r\n");
      out.write("            bottom: 20px; /* Distance from the bottom */\r\n");
      out.write("            right: 20px; /* Distance from the right */\r\n");
      out.write("            padding: 10px 15px; /* Padding for button */\r\n");
      out.write("            font-size: 16px; /* Font size */\r\n");
      out.write("            color: white; /* Text color */\r\n");
      out.write("            background-color: rgba(76, 175, 80, 0.8); /* Button background color */\r\n");
      out.write("            border: none; /* Remove border */\r\n");
      out.write("            border-radius: 5px; /* Rounded corners */\r\n");
      out.write("            cursor: pointer; /* Pointer cursor */\r\n");
      out.write("            transition: background-color 0.3s; /* Transition effect */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-button:hover {\r\n");
      out.write("            background-color: rgba(62, 142, 65, 0.8); /* Hover effect */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            table, thead, tbody, th, td, tr {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            th {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            tr {\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("                box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            td {\r\n");
      out.write("                position: relative;\r\n");
      out.write("                padding-left: 50%;\r\n");
      out.write("                text-align: right;\r\n");
      out.write("                background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("                border-bottom: 1px solid #ddd;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            td:before {\r\n");
      out.write("                content: attr(data-label);\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                width: 45%;\r\n");
      out.write("                padding-left: 15px;\r\n");
      out.write("                text-align: left;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                text-transform: uppercase;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            tr:hover {\r\n");
      out.write("                background-color: rgba(255, 255, 255, 0.8); \r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            td {\r\n");
      out.write("                font-size: 0.9em;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1 style=\"color: black; text-transform: uppercase;\">processing</h1>\r\n");
      out.write("    <table id=\"myTable\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th onclick=\"sortTable(0)\">ID</th>\r\n");
      out.write("                <th onclick=\"sortTable(1)\">Employee ID</th>\r\n");
      out.write("                <th onclick=\"sortTable(2)\">Fruits/Vegetables</th>\r\n");
      out.write("                <th onclick=\"sortTable(3)\">Remaining Tons Needed</th>\r\n");
      out.write("                <th onclick=\"sortTable(4)\">Estimated Time (Days)</th>\r\n");
      out.write("                <th onclick=\"sortTable(5)\">Total Quantity Available</th>\r\n");
      out.write("                <th onclick=\"sortTable(6)\">Projected Growth Next Month</th>\r\n");
      out.write("                <th onclick=\"sortTable(7)\">Inventory Turnover Rate</th>\r\n");
      out.write("                <th onclick=\"sortTable(8)\">Days Until Full Stock</th>\r\n");
      out.write("                <th onclick=\"sortTable(9)\">Supply Deficit</th>\r\n");
      out.write("                <th onclick=\"sortTable(10)\">Growth Potential</th>\r\n");
      out.write("                <th onclick=\"sortTable(11)\">Current Stock Status</th>\r\n");
      out.write("                <th>Calculate</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");

                // Database connection and query logic as before
                String jdbcUrl = "jdbc:mysql://localhost:3306/vertical_farming"; // Update with your database name
                String dbUser = "root"; // Update with your database username
                String dbPassword = "root"; // Update with your database password

                Connection conn = null;
                Statement stmt = null;
                ResultSet rs = null;

                try {
                    // Establishing a database connection
                    Class.forName("com.mysql.jdbc.Driver"); // Use the correct driver class
                    conn = DriverManager.getConnection(jdbcUrl, dbUser, dbPassword);
                    stmt = conn.createStatement();
                    String sql = "SELECT * FROM module2_calculated_result"; // Change the table name
                    rs = stmt.executeQuery(sql);

                    // Loop through the result set and display the data in the table
                    while (rs.next()) {
                        String currentStockStatus = rs.getString("current_stock_status"); // Get current stock status
                        boolean isAvailable = "Available".equalsIgnoreCase(currentStockStatus); // Check if status is "Available"
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td data-label=\"ID\">");
      out.print( rs.getString("id") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Employee ID\">");
      out.print( rs.getString("employee_id") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Fruits/Vegetables\">");
      out.print( rs.getString("fruits_vegetables") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Remaining Tons Needed\">");
      out.print( rs.getString("remaining_tons_needed") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Estimated Time (Days)\">");
      out.print( rs.getString("estimated_time_days") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Total Quantity Available\">");
      out.print( rs.getString("total_quantity_available") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Projected Growth Next Month\">");
      out.print( rs.getString("projected_growth_next_month") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Inventory Turnover Rate\">");
      out.print( rs.getString("inventory_turnover_rate") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Days Until Full Stock\">");
      out.print( rs.getString("days_until_full_stock") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Supply Deficit\">");
      out.print( rs.getString("supply_deficit") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Growth Potential\">");
      out.print( rs.getString("growth_potential") );
      out.write("</td>\r\n");
      out.write("                            <td data-label=\"Current Stock Status\">");
      out.print( currentStockStatus );
      out.write("</td>\r\n");
      out.write("                            <!-- New column with calculate button -->\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <form action=\"module3_cultivation_calculation.jsp\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( rs.getString("id") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"employee_id\" value=\"");
      out.print( rs.getString("employee_id") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"fruits_vegetables\" value=\"");
      out.print( rs.getString("fruits_vegetables") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"remaining_tons_needed\" value=\"");
      out.print( rs.getString("remaining_tons_needed") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"estimated_time_days\" value=\"");
      out.print( rs.getString("estimated_time_days") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"total_quantity_available\" value=\"");
      out.print( rs.getString("total_quantity_available") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"projected_growth_next_month\" value=\"");
      out.print( rs.getString("projected_growth_next_month") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"inventory_turnover_rate\" value=\"");
      out.print( rs.getString("inventory_turnover_rate") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"days_until_full_stock\" value=\"");
      out.print( rs.getString("days_until_full_stock") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"supply_deficit\" value=\"");
      out.print( rs.getString("supply_deficit") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"growth_potential\" value=\"");
      out.print( rs.getString("growth_potential") );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"current_stock_status\" value=\"");
      out.print( rs.getString("current_stock_status") );
      out.write("\">\r\n");
      out.write("                                    <button type=\"submit\" ");
      out.print( isAvailable ? "disabled" : "" );
      out.write(">Calculate</button> <!-- Disable if Available -->\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    // Closing resources
                    try {
                        if (rs != null) rs.close();
                        if (stmt != null) stmt.close();
                        if (conn != null) conn.close();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Back button -->\r\n");
      out.write("    <button class=\"back-button\" onclick=\"window.location.href='module3_cultivation_homepage.html'\">Back</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function sortTable(n) {\r\n");
      out.write("        // Sorting function implementation goes here\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
